### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by KevCron**

### CODE REVIEW

**Comment by KevCron** [comment]
PR is primarily to add the Logo model, but also gets rid of ambiguous determination of model types. PMD fixes included as well.

Also notice the ridiculous amount of commits; this is because the history of the public repo does not match the private repo. For this reason I will be discontinuing development on it and just making PRs to the public repo in the future.

**Comment by KevCron** [comment]
@jack0 any thoughts?

**Comment by jack0** [comment]
sorry what is this PR about? hard to understand given the PR title and little context. are you trying to allow for null fields?
@dcirne do you have any opinions on this PR?

**Comment by dcirne** [comment]
Sorry, I don't know the details about the code, Kevin may be the best person to elaborate on it. 

Now, regarding diverging histories, we can try to rebase this branch on top of master and solve the excessive number of commits. I can help with that.

**Comment by KevCron** [comment]
Hey @dcirne , diverging histories is fine, I am just going to squash this into a single commit anyway. It happens because we use two different repos for the Java API client.

@jack0 my apologies for any confusion, I was just looking for some general code review before I merged. Most of the diff comes from fixing PMD violations, but the logo model is also added in this PR. The last thing is changing the way the model types is determined, as determining from the "data" field in the JSON response was never a good idea in the first place.

**Comment by KevCron** [comment]
retest this please

**Pull request merged**
